### ISSUE TITLE
支持下pod呗，大神

### ISSUE THREAD

**Issue by Bretra** [DouKing/NavigationTransition#1]
支持下pod呗，大神
另外看到有内存泄漏的地方，大神

**Comment by DouKing** [comment]
支持pod的。pod 'NavigationTransition'
稍后我更新一下 readme

哪里有内存泄漏哇？谢谢指出

**Comment by DouKing** [comment]
支持pod的。pod 'NavigationTransition'
稍后我更新一下 readme

哪里有内存泄漏哇？谢谢指出

**Comment by Bretra** [comment]
我允许的demo，使用instruments扫描到的，有4个左右，您看下

**Comment by Bretra** [comment]
另外，我看了下，left这个是截屏的缘故，会导致内存增加的

**Comment by Bretra** [comment]
大神，我刚刚pod了，但是引入了另外的一个库，我看了下就使用了另外的一个库的交换方法的方法，大神，可否把这个单独写到这个库里面

**Comment by Bretra** [comment]
大神，把使用storyboard的方式，改为纯代码的形式吧

**Comment by DouKing** [comment]
好

**Comment by DouKing** [comment]
你可以用纯代码写的啊

**Comment by DouKing** [comment]
@VillageMud 已经改好。另外，我好像没发现内存泄漏呢

**Comment by Bretra** [comment]
![image](https://user-images.githubusercontent.com/12798195/45297525-3eba6880-b538-11e8-875a-81bc560641c8.png)
我这边出现三个leaks，我截图给你

**Comment by Bretra** [comment]
![image](https://user-images.githubusercontent.com/12798195/45297610-83460400-b538-11e8-80bb-089069f3185e.png)

**Comment by Bretra** [comment]
是4个leaks

**Comment by DouKing** [comment]
已经更新到1.0.1版本 pod 'NavigationTransition', '~> 1.0.1'

检查内存泄漏你用的真机还是模拟器？

**Comment by Bretra** [comment]
模拟器
![image](https://user-images.githubusercontent.com/12798195/45298019-c94f9780-b539-11e8-9329-dae5061684e7.png)

**Comment by DouKing** [comment]
你用真机检查试试，我测的没问题。
pod 清一下缓存: sudo rm -fr ~/Library/Caches/CocoaPods/
